-- 016_publish_destination.sql
-- Records where each document's published PDF is filed, and lets the publish
-- pipeline write back the resulting URL.
-- Depends on: 004 (document), 014 (grants)
--
-- WHAT LIVES WHERE
--
--   DOM              publish_folder_path  — a governance decision: which library
--                                           folder this document belongs in
--   Variable group   site id, drive id    — infrastructure identifiers that
--                                           change if the site is rebuilt, and
--                                           that sit next to the credential
--
-- The DOM should not hold Microsoft Graph GUIDs. It holds the intent ("published
-- SOPs go in this folder"); the pipeline holds the plumbing.
--
-- THE ACTUAL SHAREPOINT STRUCTURE
--
--   Site:    https://kendallgroup.sharepoint.com/sites/PMO
--   Library: Current procedures          <- this is the DRIVE
--   Folders: SOPs
--            Templates & Forms
--
-- publish_folder_path is relative to the drive root, so it is the folder name
-- alone — the library is identified by SP_DRIVE_ID in the variable group, not
-- repeated here.
--
-- "Templates & Forms" still carries an ampersand, which encodes as %26 and, left
-- unescaped, acts as a query-string separator — a bad path truncates silently
-- rather than erroring. Worth renaming on the same reasoning as the apostrophe
-- that was removed from "SOPs", if forms are ever published by the pipeline.
--
-- A NOTE ON THE published_url GRANT BELOW
--
-- Migration 014 deliberately kept published_url out of dom_writer's reach, on
-- the grounds that repointing a document is a governance decision rather than an
-- outcome of a process run.
--
-- The upload is the exception, and narrowly so: the pipeline is the thing that
-- creates that URL. It is not choosing where the document points, it is
-- recording where it just put it. Without this the DOM's idea of the published
-- location drifts from reality the first time a folder changes — the same
-- silent-staleness failure the whole project exists to remove.

BEGIN;

ALTER TABLE document ADD COLUMN publish_folder_path text;

COMMENT ON COLUMN document.publish_folder_path IS
    'Folder within the SharePoint library where the generated PDF is filed, relative to the drive root, no leading slash. NULL means this document is not generated by the pipeline — its published_url is maintained by hand.';

UPDATE document
SET    publish_folder_path = 'SOPs',
       updated_at          = now()
WHERE  document_code = 'SOP-001';

-- ---------------------------------------------------------------------------
-- FORM-001 stays NULL, deliberately.
--
-- The form's source is not in the repository (repo_path IS NULL), so nothing
-- generates it and there is nothing for the pipeline to publish. NULL means
-- "not published by this pipeline" and the upload script skips it on that basis.
--
-- The form's location is still known — published_url points at the current file
-- in SharePoint — so "Form: FORM-001" still resolves. Only the generation is
-- absent, not the reference.
--
-- If forms are later authored as Markdown and generated the same way, this
-- becomes the Templates & Forms folder.
-- ---------------------------------------------------------------------------

GRANT UPDATE (published_url) ON document TO dom_writer;

INSERT INTO schema_migration (filename, notes)
VALUES ('016_publish_destination.sql',
        'document.publish_folder_path (SOP-001 -> SOPs); dom_writer may record published_url after upload.');

COMMIT;
